defmodule Trader.TradeClient.Exchange.Binance.FixApi.Tag do
  @moduledoc "tag enum"
  def msg_type, do: "35"
  def seqnum, do: "34"
  def sender_comp_id, do: "49"
  def sending_time, do: "52"
  def target_comp_id, do: "56"
  def poss_dup_flag, do: "43"
  def orig_sending_time, do: "122"
  def encrypt_method, do: "98"
  def heartbeat_interval, do: "108"
  def raw_data_length, do: "95"
  def raw_data, do: "96"
  def reset_seq_num_flag, do: "141"
  def username, do: "553"
  def message_handling, do: "25035"
  def response_mode, do: "25036"
  def drop_copy_flag, do: "9406"
  def cl_order_id, do: "11"
  def order_type, do: "40"
  def side, do: "54"
  def symbol, do: "55"
  def cash_order_qty, do: "152"
  def order_status, do: "39"
  def quantity_base, do: "14"
  def quantity_quote, do: "25017"
  def fee_currency, do: "138"
  def fee_amount, do: "137"
  def test_request_id, do: "112"
  def reject_text, do: "58"
end
