cmake_minimum_required(VERSION 3.31 FATAL_ERROR)

project(flashfix LANGUAGES CXX C)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON) # for clangd
set(CMAKE_CXX_STANDARD 17)

# Add sanitizers + other helpful flags in debug builds
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -O0 -Wall -Wextra -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer")
set(CMAKE_LINKER_FLAGS_DEBUG "${CMAKE_LINKER_FLAGS_DEBUG} -fsanitize=address -fsanitize=undefined")

# add option to build other targets
option(flashfix_TESTS "Build flashfix tests" ON)

# add libdpdk, libfstack, libmt dependencies
find_package(OpenSSL REQUIRED)
find_package(jansson REQUIRED)
find_package(PkgConfig REQUIRED)
pkg_check_modules(LIBDPDK REQUIRED libdpdk)
find_package(fstack REQUIRED)



add_library(${PROJECT_NAME} SHARED
  src/DataDictionary.cpp
  src/DataDictionaryProvider.cpp
  src/Dictionary.cpp
  src/FieldConvertors.cpp
  src/FieldMap.cpp
  src/FieldTypes.cpp
  src/FileLog.cpp
  src/FileStore.cpp
  src/Group.cpp
  src/HostDetailsProvider.cpp
  src/Initiator.cpp
  src/Log.cpp
  src/Message.cpp
  src/MessageSorters.cpp
  src/MessageStore.cpp
  src/NullStore.cpp
  src/Parser.cpp
  src/pugixml.cpp
  src/PUGIXML_DOMDocument.cpp
  src/Session.cpp
  src/SessionFactory.cpp
  src/SessionSettings.cpp
  src/Settings.cpp
  src/stdafx.cpp
  src/TimeRange.cpp
  src/Utility.cpp
  src/FstackMicroThreadedSSLSocketInitiator.cpp
  src/FstackMicroThreadedSSLSocketConnection.cpp
  src/FStackSSLBIO.cpp
  src/UtilitySSL.cpp
  src/double-conversion/strtod.cc
  src/double-conversion/bignum-dtoa.cc
  src/double-conversion/fast-dtoa.cc
  src/double-conversion/cached-powers.cc
  src/double-conversion/bignum.cc
  src/double-conversion/diy-fp.cc
  src/double-conversion/double-conversion.cc
  src/double-conversion/fixed-dtoa.cc
)

target_sources(${PROJECT_NAME}
  PRIVATE
  FILE_SET private_headers
  TYPE HEADERS
  BASE_DIRS include/double-conversion
  FILES
    include/double-conversion/ieee.h
    include/double-conversion/fast-dtoa.h
    include/double-conversion/fixed-dtoa.h
    include/double-conversion/utils.h
    include/double-conversion/strtod.h
    include/double-conversion/diy-fp.h
    include/double-conversion/cached-powers.h
    include/double-conversion/bignum-dtoa.h
    include/double-conversion/double-conversion.h
    include/double-conversion/bignum.h
)
target_sources(${PROJECT_NAME}
  PUBLIC 
  FILE_SET public_headers
  TYPE HEADERS
  BASE_DIRS include
  FILES
    include/fix50sp1/QuoteStatusReport.h
    include/fix50sp1/QuoteRequest.h
    include/fix50sp1/MarketDataRequestReject.h
    include/fix50sp1/TradingSessionList.h
    include/fix50sp1/MarketDefinitionRequest.h
    include/fix50sp1/OrderMassCancelRequest.h
    include/fix50sp1/AssignmentReport.h
    include/fix50sp1/Email.h
    include/fix50sp1/IOI.h
    include/fix50sp1/ConfirmationRequest.h
    include/fix50sp1/RegistrationInstructions.h
    include/fix50sp1/RequestForPositionsAck.h
    include/fix50sp1/CollateralInquiry.h
    include/fix50sp1/SecurityStatusRequest.h
    include/fix50sp1/SecurityListUpdateReport.h
    include/fix50sp1/SettlementObligationReport.h
    include/fix50sp1/OrderCancelRequest.h
    include/fix50sp1/TradingSessionStatusRequest.h
    include/fix50sp1/TradeCaptureReportRequestAck.h
    include/fix50sp1/SecurityDefinition.h
    include/fix50sp1/ApplicationMessageRequest.h
    include/fix50sp1/SecurityTypes.h
    include/fix50sp1/NetworkCounterpartySystemStatusResponse.h
    include/fix50sp1/CrossOrderCancelRequest.h
    include/fix50sp1/AllocationInstructionAlert.h
    include/fix50sp1/DerivativeSecurityListRequest.h
    include/fix50sp1/ListExecute.h
    include/fix50sp1/CollateralRequest.h
    include/fix50sp1/RequestForPositions.h
    include/fix50sp1/SecurityDefinitionUpdateReport.h
    include/fix50sp1/OrderCancelReject.h
    include/fix50sp1/Confirmation.h
    include/fix50sp1/MarketDataRequest.h
    include/fix50sp1/Advertisement.h
    include/fix50sp1/SecurityStatus.h
    include/fix50sp1/MassQuote.h
    include/fix50sp1/QuoteStatusRequest.h
    include/fix50sp1/NetworkCounterpartySystemStatusRequest.h
    include/fix50sp1/DerivativeSecurityListUpdateReport.h
    include/fix50sp1/QuoteRequestReject.h
    include/fix50sp1/PositionMaintenanceRequest.h
    include/fix50sp1/ApplicationMessageReport.h
    include/fix50sp1/SecurityDefinitionRequest.h
    include/fix50sp1/DerivativeSecurityList.h
    include/fix50sp1/NewOrderList.h
    include/fix50sp1/SecurityList.h
    include/fix50sp1/TradingSessionListRequest.h
    include/fix50sp1/OrderMassActionReport.h
    include/fix50sp1/BidResponse.h
    include/fix50sp1/OrderMassCancelReport.h
    include/fix50sp1/BidRequest.h
    include/fix50sp1/News.h
    include/fix50sp1/AllocationInstruction.h
    include/fix50sp1/ConfirmationAck.h
    include/fix50sp1/MassQuoteAcknowledgement.h
    include/fix50sp1/OrderMassActionRequest.h
    include/fix50sp1/SecurityTypeRequest.h
    include/fix50sp1/ListStatusRequest.h
    include/fix50sp1/QuoteCancel.h
    include/fix50sp1/UserRequest.h
    include/fix50sp1/ListStrikePrice.h
    include/fix50sp1/ContraryIntentionReport.h
    include/fix50sp1/RegistrationInstructionsResponse.h
    include/fix50sp1/AllocationReport.h
    include/fix50sp1/CrossOrderCancelReplaceRequest.h
    include/fix50sp1/RFQRequest.h
    include/fix50sp1/Quote.h
    include/fix50sp1/ExecutionReport.h
    include/fix50sp1/MessageCracker.h
    include/fix50sp1/AllocationInstructionAck.h
    include/fix50sp1/TradeCaptureReportAck.h
    include/fix50sp1/MarketDataSnapshotFullRefresh.h
    include/fix50sp1/AllocationReportAck.h
    include/fix50sp1/PositionMaintenanceReport.h
    include/fix50sp1/SecurityListRequest.h
    include/fix50sp1/TradingSessionListUpdateReport.h
    include/fix50sp1/DontKnowTrade.h
    include/fix50sp1/NewOrderSingle.h
    include/fix50sp1/ExecutionAcknowledgement.h
    include/fix50sp1/SettlementInstructions.h
    include/fix50sp1/PositionReport.h
    include/fix50sp1/NewOrderMultileg.h
    include/fix50sp1/CollateralAssignment.h
    include/fix50sp1/Message.h
    include/fix50sp1/OrderCancelReplaceRequest.h
    include/fix50sp1/BusinessMessageReject.h
    include/fix50sp1/CollateralReport.h
    include/fix50sp1/UserResponse.h
    include/fix50sp1/ListStatus.h
    include/fix50sp1/NewOrderCross.h
    include/fix50sp1/MarketDataIncrementalRefresh.h
    include/fix50sp1/MultilegOrderCancelReplace.h
    include/fix50sp1/OrderMassStatusRequest.h
    include/fix50sp1/TradeCaptureReport.h
    include/fix50sp1/MarketDefinition.h
    include/fix50sp1/TradeCaptureReportRequest.h
    include/fix50sp1/AdjustedPositionReport.h
    include/fix50sp1/CollateralInquiryAck.h
    include/fix50sp1/CollateralResponse.h
    include/fix50sp1/ApplicationMessageRequestAck.h
    include/fix50sp1/MarketDefinitionUpdateReport.h
    include/fix50sp1/ListCancelRequest.h
    include/fix50sp1/QuoteResponse.h
    include/fix50sp1/TradingSessionStatus.h
    include/fix50sp1/UserNotification.h
    include/fix50sp1/OrderStatusRequest.h
    include/fix50sp1/SettlementInstructionRequest.h
    include/stdafx.h
    include/Responder.h
    include/Log.h
    include/Session.h
    include/FileStore.h
    include/index.h
    include/Event.h
    include/Group.h
    include/FixFieldNumbers.h
    include/FixValues.h
    include/fix43/QuoteStatusReport.h
    include/fix43/QuoteRequest.h
    include/fix43/Reject.h
    include/fix43/MarketDataRequestReject.h
    include/fix43/TestRequest.h
    include/fix43/OrderMassCancelRequest.h
    include/fix43/Email.h
    include/fix43/IOI.h
    include/fix43/Logon.h
    include/fix43/RegistrationInstructions.h
    include/fix43/SecurityStatusRequest.h
    include/fix43/OrderCancelRequest.h
    include/fix43/TradingSessionStatusRequest.h
    include/fix43/Heartbeat.h
    include/fix43/SecurityDefinition.h
    include/fix43/SecurityTypes.h
    include/fix43/CrossOrderCancelRequest.h
    include/fix43/DerivativeSecurityListRequest.h
    include/fix43/ListExecute.h
    include/fix43/OrderCancelReject.h
    include/fix43/MarketDataRequest.h
    include/fix43/Advertisement.h
    include/fix43/SecurityStatus.h
    include/fix43/MassQuote.h
    include/fix43/SequenceReset.h
    include/fix43/QuoteStatusRequest.h
    include/fix43/QuoteRequestReject.h
    include/fix43/SecurityDefinitionRequest.h
    include/fix43/DerivativeSecurityList.h
    include/fix43/NewOrderList.h
    include/fix43/SecurityList.h
    include/fix43/BidResponse.h
    include/fix43/OrderMassCancelReport.h
    include/fix43/BidRequest.h
    include/fix43/News.h
    include/fix43/MassQuoteAcknowledgement.h
    include/fix43/SecurityTypeRequest.h
    include/fix43/Logout.h
    include/fix43/ListStatusRequest.h
    include/fix43/QuoteCancel.h
    include/fix43/ListStrikePrice.h
    include/fix43/RegistrationInstructionsResponse.h
    include/fix43/CrossOrderCancelReplaceRequest.h
    include/fix43/XMLnonFIX.h
    include/fix43/RFQRequest.h
    include/fix43/Quote.h
    include/fix43/ExecutionReport.h
    include/fix43/MessageCracker.h
    include/fix43/MultilegOrderCancelReplaceRequest.h
    include/fix43/MarketDataSnapshotFullRefresh.h
    include/fix43/SecurityListRequest.h
    include/fix43/DontKnowTrade.h
    include/fix43/NewOrderSingle.h
    include/fix43/SettlementInstructions.h
    include/fix43/NewOrderMultileg.h
    include/fix43/Message.h
    include/fix43/OrderCancelReplaceRequest.h
    include/fix43/BusinessMessageReject.h
    include/fix43/ListStatus.h
    include/fix43/NewOrderCross.h
    include/fix43/MarketDataIncrementalRefresh.h
    include/fix43/ResendRequest.h
    include/fix43/OrderMassStatusRequest.h
    include/fix43/TradeCaptureReport.h
    include/fix43/TradeCaptureReportRequest.h
    include/fix43/AllocationAck.h
    include/fix43/Allocation.h
    include/fix43/ListCancelRequest.h
    include/fix43/TradingSessionStatus.h
    include/fix43/OrderStatusRequest.h
    include/fix44/QuoteStatusReport.h
    include/fix44/QuoteRequest.h
    include/fix44/Reject.h
    include/fix44/MarketDataRequestReject.h
    include/fix44/TestRequest.h
    include/fix44/OrderMassCancelRequest.h
    include/fix44/AssignmentReport.h
    include/fix44/Email.h
    include/fix44/IOI.h
    include/fix44/Logon.h
    include/fix44/ConfirmationRequest.h
    include/fix44/RegistrationInstructions.h
    include/fix44/RequestForPositionsAck.h
    include/fix44/CollateralInquiry.h
    include/fix44/SecurityStatusRequest.h
    include/fix44/OrderCancelRequest.h
    include/fix44/TradingSessionStatusRequest.h
    include/fix44/TradeCaptureReportRequestAck.h
    include/fix44/Heartbeat.h
    include/fix44/SecurityDefinition.h
    include/fix44/SecurityTypes.h
    include/fix44/NetworkCounterpartySystemStatusResponse.h
    include/fix44/CrossOrderCancelRequest.h
    include/fix44/DerivativeSecurityListRequest.h
    include/fix44/ListExecute.h
    include/fix44/CollateralRequest.h
    include/fix44/RequestForPositions.h
    include/fix44/OrderCancelReject.h
    include/fix44/Confirmation.h
    include/fix44/MarketDataRequest.h
    include/fix44/Advertisement.h
    include/fix44/SecurityStatus.h
    include/fix44/MassQuote.h
    include/fix44/SequenceReset.h
    include/fix44/QuoteStatusRequest.h
    include/fix44/NetworkCounterpartySystemStatusRequest.h
    include/fix44/QuoteRequestReject.h
    include/fix44/PositionMaintenanceRequest.h
    include/fix44/SecurityDefinitionRequest.h
    include/fix44/DerivativeSecurityList.h
    include/fix44/NewOrderList.h
    include/fix44/SecurityList.h
    include/fix44/BidResponse.h
    include/fix44/OrderMassCancelReport.h
    include/fix44/BidRequest.h
    include/fix44/News.h
    include/fix44/AllocationInstruction.h
    include/fix44/ConfirmationAck.h
    include/fix44/MassQuoteAcknowledgement.h
    include/fix44/SecurityTypeRequest.h
    include/fix44/Logout.h
    include/fix44/ListStatusRequest.h
    include/fix44/QuoteCancel.h
    include/fix44/UserRequest.h
    include/fix44/ListStrikePrice.h
    include/fix44/RegistrationInstructionsResponse.h
    include/fix44/AllocationReport.h
    include/fix44/CrossOrderCancelReplaceRequest.h
    include/fix44/XMLnonFIX.h
    include/fix44/RFQRequest.h
    include/fix44/Quote.h
    include/fix44/ExecutionReport.h
    include/fix44/MessageCracker.h
    include/fix44/AllocationInstructionAck.h
    include/fix44/TradeCaptureReportAck.h
    include/fix44/MarketDataSnapshotFullRefresh.h
    include/fix44/AllocationReportAck.h
    include/fix44/PositionMaintenanceReport.h
    include/fix44/SecurityListRequest.h
    include/fix44/DontKnowTrade.h
    include/fix44/NewOrderSingle.h
    include/fix44/SettlementInstructions.h
    include/fix44/PositionReport.h
    include/fix44/NewOrderMultileg.h
    include/fix44/CollateralAssignment.h
    include/fix44/Message.h
    include/fix44/OrderCancelReplaceRequest.h
    include/fix44/BusinessMessageReject.h
    include/fix44/CollateralReport.h
    include/fix44/UserResponse.h
    include/fix44/ListStatus.h
    include/fix44/NewOrderCross.h
    include/fix44/MarketDataIncrementalRefresh.h
    include/fix44/MultilegOrderCancelReplace.h
    include/fix44/ResendRequest.h
    include/fix44/OrderMassStatusRequest.h
    include/fix44/TradeCaptureReport.h
    include/fix44/TradeCaptureReportRequest.h
    include/fix44/CollateralInquiryAck.h
    include/fix44/CollateralResponse.h
    include/fix44/ListCancelRequest.h
    include/fix44/QuoteResponse.h
    include/fix44/TradingSessionStatus.h
    include/fix44/OrderStatusRequest.h
    include/fix44/SettlementInstructionRequest.h
    include/Fields.h
    include/FileLog.h
    include/Application.h
    include/FixCommonFields.h
    include/fix50/QuoteStatusReport.h
    include/fix50/QuoteRequest.h
    include/fix50/MarketDataRequestReject.h
    include/fix50/TradingSessionList.h
    include/fix50/OrderMassCancelRequest.h
    include/fix50/AssignmentReport.h
    include/fix50/Email.h
    include/fix50/IOI.h
    include/fix50/ConfirmationRequest.h
    include/fix50/RegistrationInstructions.h
    include/fix50/RequestForPositionsAck.h
    include/fix50/CollateralInquiry.h
    include/fix50/SecurityStatusRequest.h
    include/fix50/SecurityListUpdateReport.h
    include/fix50/OrderCancelRequest.h
    include/fix50/TradingSessionStatusRequest.h
    include/fix50/TradeCaptureReportRequestAck.h
    include/fix50/SecurityDefinition.h
    include/fix50/SecurityTypes.h
    include/fix50/NetworkCounterpartySystemStatusResponse.h
    include/fix50/CrossOrderCancelRequest.h
    include/fix50/AllocationInstructionAlert.h
    include/fix50/DerivativeSecurityListRequest.h
    include/fix50/ListExecute.h
    include/fix50/CollateralRequest.h
    include/fix50/RequestForPositions.h
    include/fix50/SecurityDefinitionUpdateReport.h
    include/fix50/OrderCancelReject.h
    include/fix50/Confirmation.h
    include/fix50/MarketDataRequest.h
    include/fix50/Advertisement.h
    include/fix50/SecurityStatus.h
    include/fix50/MassQuote.h
    include/fix50/QuoteStatusRequest.h
    include/fix50/NetworkCounterpartySystemStatusRequest.h
    include/fix50/QuoteRequestReject.h
    include/fix50/PositionMaintenanceRequest.h
    include/fix50/SecurityDefinitionRequest.h
    include/fix50/DerivativeSecurityList.h
    include/fix50/NewOrderList.h
    include/fix50/SecurityList.h
    include/fix50/TradingSessionListRequest.h
    include/fix50/BidResponse.h
    include/fix50/OrderMassCancelReport.h
    include/fix50/BidRequest.h
    include/fix50/News.h
    include/fix50/AllocationInstruction.h
    include/fix50/ConfirmationAck.h
    include/fix50/MassQuoteAcknowledgement.h
    include/fix50/SecurityTypeRequest.h
    include/fix50/ListStatusRequest.h
    include/fix50/QuoteCancel.h
    include/fix50/UserRequest.h
    include/fix50/ListStrikePrice.h
    include/fix50/ContraryIntentionReport.h
    include/fix50/RegistrationInstructionsResponse.h
    include/fix50/AllocationReport.h
    include/fix50/CrossOrderCancelReplaceRequest.h
    include/fix50/RFQRequest.h
    include/fix50/Quote.h
    include/fix50/ExecutionReport.h
    include/fix50/MessageCracker.h
    include/fix50/AllocationInstructionAck.h
    include/fix50/TradeCaptureReportAck.h
    include/fix50/MarketDataSnapshotFullRefresh.h
    include/fix50/AllocationReportAck.h
    include/fix50/PositionMaintenanceReport.h
    include/fix50/SecurityListRequest.h
    include/fix50/DontKnowTrade.h
    include/fix50/NewOrderSingle.h
    include/fix50/ExecutionAcknowledgement.h
    include/fix50/SettlementInstructions.h
    include/fix50/PositionReport.h
    include/fix50/NewOrderMultileg.h
    include/fix50/CollateralAssignment.h
    include/fix50/Message.h
    include/fix50/OrderCancelReplaceRequest.h
    include/fix50/BusinessMessageReject.h
    include/fix50/CollateralReport.h
    include/fix50/UserResponse.h
    include/fix50/ListStatus.h
    include/fix50/NewOrderCross.h
    include/fix50/MarketDataIncrementalRefresh.h
    include/fix50/MultilegOrderCancelReplace.h
    include/fix50/OrderMassStatusRequest.h
    include/fix50/TradeCaptureReport.h
    include/fix50/TradeCaptureReportRequest.h
    include/fix50/AdjustedPositionReport.h
    include/fix50/CollateralInquiryAck.h
    include/fix50/CollateralResponse.h
    include/fix50/ListCancelRequest.h
    include/fix50/QuoteResponse.h
    include/fix50/TradingSessionStatus.h
    include/fix50/OrderStatusRequest.h
    include/fix50/SettlementInstructionRequest.h
    include/Values.h
    include/config.h
    include/Utility.h
    include/FstackMicroThreadedSSLSocketInitiator.h
    include/Allocator.h
    include/Settings.h
    include/MessageSorters.h
    include/Exceptions.h
    include/SessionFactory.h
    include/FixFields.h
    include/Field.h
    include/SessionState.h
    include/fix50sp2/TradeMatchReport.h
    include/fix50sp2/QuoteStatusReport.h
    include/fix50sp2/QuoteRequest.h
    include/fix50sp2/MarketDataRequestReject.h
    include/fix50sp2/TradingSessionList.h
    include/fix50sp2/MarketDefinitionRequest.h
    include/fix50sp2/PartyDetailsDefinitionRequestAck.h
    include/fix50sp2/OrderMassCancelRequest.h
    include/fix50sp2/AssignmentReport.h
    include/fix50sp2/StreamAssignmentReport.h
    include/fix50sp2/Email.h
    include/fix50sp2/PayManagementRequestAck.h
    include/fix50sp2/IOI.h
    include/fix50sp2/PositionTransferInstructionAck.h
    include/fix50sp2/PartyRiskLimitsDefinitionRequest.h
    include/fix50sp2/ConfirmationRequest.h
    include/fix50sp2/PartyEntitlementsReport.h
    include/fix50sp2/MassQuoteAck.h
    include/fix50sp2/RegistrationInstructions.h
    include/fix50sp2/RequestForPositionsAck.h
    include/fix50sp2/CollateralInquiry.h
    include/fix50sp2/SecurityStatusRequest.h
    include/fix50sp2/PartyDetailsListUpdateReport.h
    include/fix50sp2/PartyActionReport.h
    include/fix50sp2/SecurityListUpdateReport.h
    include/fix50sp2/SettlementObligationReport.h
    include/fix50sp2/PartyRiskLimitsReportAck.h
    include/fix50sp2/PartyRiskLimitsReport.h
    include/fix50sp2/MarginRequirementInquiry.h
    include/fix50sp2/StreamAssignmentReportACK.h
    include/fix50sp2/AllocationInstructionAlertRequestAck.h
    include/fix50sp2/OrderCancelRequest.h
    include/fix50sp2/MarketDataStatisticsRequest.h
    include/fix50sp2/TradingSessionStatusRequest.h
    include/fix50sp2/TradeAggregationReport.h
    include/fix50sp2/TradeCaptureReportRequestAck.h
    include/fix50sp2/SecurityDefinition.h
    include/fix50sp2/ApplicationMessageRequest.h
    include/fix50sp2/PartyEntitlementsDefinitionRequestAck.h
    include/fix50sp2/SecurityTypes.h
    include/fix50sp2/NetworkCounterpartySystemStatusResponse.h
    include/fix50sp2/CrossOrderCancelRequest.h
    include/fix50sp2/SecurityMassStatusRequest.h
    include/fix50sp2/AllocationInstructionAlert.h
    include/fix50sp2/DerivativeSecurityListRequest.h
    include/fix50sp2/ListExecute.h
    include/fix50sp2/CollateralRequest.h
    include/fix50sp2/RequestForPositions.h
    include/fix50sp2/MassOrder.h
    include/fix50sp2/SecurityDefinitionUpdateReport.h
    include/fix50sp2/OrderCancelReject.h
    include/fix50sp2/Confirmation.h
    include/fix50sp2/MarketDataRequest.h
    include/fix50sp2/Advertisement.h
    include/fix50sp2/MarginRequirementInquiryAck.h
    include/fix50sp2/SecurityStatus.h
    include/fix50sp2/MassQuote.h
    include/fix50sp2/QuoteStatusRequest.h
    include/fix50sp2/NetworkCounterpartySystemStatusRequest.h
    include/fix50sp2/DerivativeSecurityListUpdateReport.h
    include/fix50sp2/TradeAggregationRequest.h
    include/fix50sp2/QuoteRequestReject.h
    include/fix50sp2/PositionMaintenanceRequest.h
    include/fix50sp2/ApplicationMessageReport.h
    include/fix50sp2/SecurityDefinitionRequest.h
    include/fix50sp2/DerivativeSecurityList.h
    include/fix50sp2/NewOrderList.h
    include/fix50sp2/SecurityList.h
    include/fix50sp2/TradingSessionListRequest.h
    include/fix50sp2/OrderMassActionReport.h
    include/fix50sp2/MarketDataReport.h
    include/fix50sp2/BidResponse.h
    include/fix50sp2/OrderMassCancelReport.h
    include/fix50sp2/BidRequest.h
    include/fix50sp2/PositionTransferReport.h
    include/fix50sp2/News.h
    include/fix50sp2/AllocationInstruction.h
    include/fix50sp2/ConfirmationAck.h
    include/fix50sp2/PartyRiskLimitCheckRequestAck.h
    include/fix50sp2/MassQuoteAcknowledgement.h
    include/fix50sp2/OrderMassActionRequest.h
    include/fix50sp2/SecurityTypeRequest.h
    include/fix50sp2/PartyEntitlementsUpdateReport.h
    include/fix50sp2/ListStatusRequest.h
    include/fix50sp2/QuoteCancel.h
    include/fix50sp2/UserRequest.h
    include/fix50sp2/ListStrikePrice.h
    include/fix50sp2/ContraryIntentionReport.h
    include/fix50sp2/RegistrationInstructionsResponse.h
    include/fix50sp2/AllocationReport.h
    include/fix50sp2/AllocationInstructionAlertRequest.h
    include/fix50sp2/CrossOrderCancelReplaceRequest.h
    include/fix50sp2/StreamAssignmentRequest.h
    include/fix50sp2/MarketDataStatisticsReport.h
    include/fix50sp2/RFQRequest.h
    include/fix50sp2/PartyDetailsListRequest.h
    include/fix50sp2/Quote.h
    include/fix50sp2/ExecutionReport.h
    include/fix50sp2/MessageCracker.h
    include/fix50sp2/AllocationInstructionAck.h
    include/fix50sp2/PositionTransferInstruction.h
    include/fix50sp2/PartyRiskLimitCheckRequest.h
    include/fix50sp2/CrossRequest.h
    include/fix50sp2/TradeCaptureReportAck.h
    include/fix50sp2/MarketDataSnapshotFullRefresh.h
    include/fix50sp2/AllocationReportAck.h
    include/fix50sp2/PositionMaintenanceReport.h
    include/fix50sp2/SecurityListRequest.h
    include/fix50sp2/TradeMatchReportAck.h
    include/fix50sp2/TradingSessionListUpdateReport.h
    include/fix50sp2/DontKnowTrade.h
    include/fix50sp2/NewOrderSingle.h
    include/fix50sp2/ExecutionAcknowledgement.h
    include/fix50sp2/PartyDetailsListReport.h
    include/fix50sp2/SettlementInstructions.h
    include/fix50sp2/PartyRiskLimitsUpdateReport.h
    include/fix50sp2/PayManagementReport.h
    include/fix50sp2/PositionReport.h
    include/fix50sp2/PayManagementReportAck.h
    include/fix50sp2/QuoteAck.h
    include/fix50sp2/NewOrderMultileg.h
    include/fix50sp2/PartyDetailsDefinitionRequest.h
    include/fix50sp2/CollateralAssignment.h
    include/fix50sp2/PayManagementRequest.h
    include/fix50sp2/Message.h
    include/fix50sp2/OrderCancelReplaceRequest.h
    include/fix50sp2/BusinessMessageReject.h
    include/fix50sp2/CollateralReport.h
    include/fix50sp2/UserResponse.h
    include/fix50sp2/ListStatus.h
    include/fix50sp2/NewOrderCross.h
    include/fix50sp2/MarketDataIncrementalRefresh.h
    include/fix50sp2/MultilegOrderCancelReplace.h
    include/fix50sp2/PartyRiskLimitsRequest.h
    include/fix50sp2/ExecutionAck.h
    include/fix50sp2/PartyActionRequest.h
    include/fix50sp2/OrderMassStatusRequest.h
    include/fix50sp2/TradeCaptureReport.h
    include/fix50sp2/MarketDefinition.h
    include/fix50sp2/AccountSummaryReport.h
    include/fix50sp2/TradeCaptureReportRequest.h
    include/fix50sp2/CrossRequestAck.h
    include/fix50sp2/AdjustedPositionReport.h
    include/fix50sp2/PartyEntitlementsRequest.h
    include/fix50sp2/CollateralInquiryAck.h
    include/fix50sp2/SecurityMassStatus.h
    include/fix50sp2/CollateralReportAck.h
    include/fix50sp2/PartyRiskLimitsDefinitionRequestAck.h
    include/fix50sp2/CollateralResponse.h
    include/fix50sp2/PartyEntitlementsDefinitionRequest.h
    include/fix50sp2/ApplicationMessageRequestAck.h
    include/fix50sp2/MarketDefinitionUpdateReport.h
    include/fix50sp2/ListCancelRequest.h
    include/fix50sp2/QuoteResponse.h
    include/fix50sp2/TradingSessionStatus.h
    include/fix50sp2/UserNotification.h
    include/fix50sp2/MassOrderAck.h
    include/fix50sp2/MarginRequirementReport.h
    include/fix50sp2/OrderStatusRequest.h
    include/fix50sp2/SettlementInstructionRequest.h
    include/wx/Reject.h
    include/wx/TestRequest.h
    include/wx/Logon.h
    include/wx/Heartbeat.h
    include/wx/SequenceReset.h
    include/wx/Logout.h
    include/wx/XMLnonFIX.h
    include/wx/MessageCracker.h
    include/wx/Message.h
    include/wx/ResendRequest.h
    include/getopt-repl.h
    include/fix41/QuoteRequest.h
    include/fix41/Reject.h
    include/fix41/TestRequest.h
    include/fix41/Email.h
    include/fix41/IOI.h
    include/fix41/Logon.h
    include/fix41/OrderCancelRequest.h
    include/fix41/Heartbeat.h
    include/fix41/ListExecute.h
    include/fix41/OrderCancelReject.h
    include/fix41/Advertisement.h
    include/fix41/SequenceReset.h
    include/fix41/NewOrderList.h
    include/fix41/News.h
    include/fix41/Logout.h
    include/fix41/ListStatusRequest.h
    include/fix41/Quote.h
    include/fix41/ExecutionReport.h
    include/fix41/MessageCracker.h
    include/fix41/AllocationInstructionAck.h
    include/fix41/DontKnowTrade.h
    include/fix41/NewOrderSingle.h
    include/fix41/SettlementInstructions.h
    include/fix41/Message.h
    include/fix41/OrderCancelReplaceRequest.h
    include/fix41/ListStatus.h
    include/fix41/ResendRequest.h
    include/fix41/Allocation.h
    include/fix41/ListCancelRequest.h
    include/fix41/OrderStatusRequest.h
    include/FieldMap.h
    include/DataDictionaryProvider.h
    include/FieldTypes.h
    include/Queue.h
    include/PUGIXML_DOMDocument.h
    include/DOMDocument.h
    include/FieldConvertors.h
    include/SharedArray.h
    include/FieldNumbers.h
    include/SessionSettings.h
    include/MessageCracker.h
    include/fix42/QuoteRequest.h
    include/fix42/Reject.h
    include/fix42/MarketDataRequestReject.h
    include/fix42/TestRequest.h
    include/fix42/Email.h
    include/fix42/IOI.h
    include/fix42/Logon.h
    include/fix42/SecurityStatusRequest.h
    include/fix42/OrderCancelRequest.h
    include/fix42/TradingSessionStatusRequest.h
    include/fix42/Heartbeat.h
    include/fix42/SecurityDefinition.h
    include/fix42/QuoteAcknowledgement.h
    include/fix42/ListExecute.h
    include/fix42/OrderCancelReject.h
    include/fix42/MarketDataRequest.h
    include/fix42/Advertisement.h
    include/fix42/SecurityStatus.h
    include/fix42/MassQuote.h
    include/fix42/SequenceReset.h
    include/fix42/QuoteStatusRequest.h
    include/fix42/SecurityDefinitionRequest.h
    include/fix42/NewOrderList.h
    include/fix42/BidResponse.h
    include/fix42/BidRequest.h
    include/fix42/News.h
    include/fix42/Logout.h
    include/fix42/ListStatusRequest.h
    include/fix42/QuoteCancel.h
    include/fix42/ListStrikePrice.h
    include/fix42/Quote.h
    include/fix42/ExecutionReport.h
    include/fix42/MessageCracker.h
    include/fix42/AllocationInstructionAck.h
    include/fix42/MarketDataSnapshotFullRefresh.h
    include/fix42/DontKnowTrade.h
    include/fix42/NewOrderSingle.h
    include/fix42/SettlementInstructions.h
    include/fix42/Message.h
    include/fix42/OrderCancelReplaceRequest.h
    include/fix42/BusinessMessageReject.h
    include/fix42/ListStatus.h
    include/fix42/MarketDataIncrementalRefresh.h
    include/fix42/ResendRequest.h
    include/fix42/Allocation.h
    include/fix42/ListCancelRequest.h
    include/fix42/TradingSessionStatus.h
    include/fix42/OrderStatusRequest.h
    include/SessionID.h
    include/fixt11/Reject.h
    include/fixt11/TestRequest.h
    include/fixt11/Logon.h
    include/fixt11/Heartbeat.h
    include/fixt11/SequenceReset.h
    include/fixt11/Logout.h
    include/fixt11/XMLnonFIX.h
    include/fixt11/MessageCracker.h
    include/fixt11/Message.h
    include/fixt11/ResendRequest.h
    include/HostDetailsProvider.h
    include/TimeRange.h
    include/pugiconfig.hpp
    include/DataDictionary.h
    include/pugixml.hpp
    include/fix40/QuoteRequest.h
    include/fix40/Reject.h
    include/fix40/TestRequest.h
    include/fix40/Email.h
    include/fix40/IOI.h
    include/fix40/Logon.h
    include/fix40/OrderCancelRequest.h
    include/fix40/Heartbeat.h
    include/fix40/ListExecute.h
    include/fix40/OrderCancelReject.h
    include/fix40/Advertisement.h
    include/fix40/SequenceReset.h
    include/fix40/NewOrderList.h
    include/fix40/News.h
    include/fix40/Logout.h
    include/fix40/ListStatusRequest.h
    include/fix40/Quote.h
    include/fix40/ExecutionReport.h
    include/fix40/MessageCracker.h
    include/fix40/AllocationInstructionAck.h
    include/fix40/DontKnowTrade.h
    include/fix40/NewOrderSingle.h
    include/fix40/Message.h
    include/fix40/OrderCancelReplaceRequest.h
    include/fix40/ListStatus.h
    include/fix40/ResendRequest.h
    include/fix40/Allocation.h
    include/fix40/ListCancelRequest.h
    include/fix40/OrderStatusRequest.h
    include/config-all.h
    include/Mutex.h
    include/UtilitySSL.h
    include/Message.h
    include/MessageStore.h
    include/NullStore.h
    include/FStackSSLBIO.h
    include/Initiator.h
    include/Dictionary.h
    include/FstackMicroThreadedSSLSocketConnection.h
    include/scope_guard.hpp
    include/Parser.h
    include/Except.h
)

target_link_libraries(${PROJECT_NAME} PUBLIC ${OPENSSL_LIBRARIES} pthread fstack::fstack jansson::jansson libpcap::libpcap ${LIBDPDK_LIBRARIES} rte_net_bond)

set_target_properties(${PROJECT_NAME} PROPERTIES VERSION 1.0.0 SOVERSION 1)

# include standard installation variables
include(GNUInstallDirs)

# Install library
install(TARGETS ${PROJECT_NAME}
  EXPORT ${PROJECT_NAME}Targets
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}

  # install headers
  FILE_SET public_headers
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)

# Install FIX specification files to /share
install(DIRECTORY spec 
  DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}
  FILES_MATCHING PATTERN "FIX*.xml"
)

# Generate and install pkg-config file
#configure_file(flashfix.pc.in flashfix.pc @ONLY)
#install(FILES ${CMAKE_BINARY_DIR}/flashfix.pc DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)

# TESTS
if (flashfix_TESTS)
    add_subdirectory(test)
endif()
