---
binance_rest_api_uri: "https://api.binance.com"
binance_fix_api_hostname_orderentry: "fix-oe.binance.com"
binance_fix_api_hostname_marketdata: "fix-md.binance.com"
binance_ed25519_seed: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35393931633935333437383634336330656334663664346665363237356434396566656231646665
  3463653732643032663864646536333932623139623238350a343064343838636466303437366264
  62636336373630333631353464316366383930656661623766346235366131666164336239613430
  6163353735393835630a636531346134653331316330373666343463623862623730643530383731
  33653866636134613964613830393864646432373861633036323332353564363530656665623434
  6135646237383138373935303931623663396365396432623065
binance_ed25519_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66373033386333653538663064656438386361396133376635383466336435326530316436653364
  6338396232643730666566306164306338653731666635340a666139323566653864393864383331
  63326463363666666563613161346338306139313939336265393831336665626437346464383436
  3063393662653238630a373734313463663230643038663730653638326237646363643530353636
  30343732383933663964386566343837373533326162653263333463323937373666623466343565
  30313933643532366563363738323730646431663966626164663237303838633763646338626561
  33333631383230303462666134383861663032643266636630396236353663343865666630373861
  32636563363336323339
max_trading_path_length: 3
# all in prod except USDT,FDUSD,TUSD,USDP,DAI,AEUR,UST,USTC,PAXG
assets: >
  0G,
  1000CAT,
  1000CHEEMS,
  1000SATS,
  1INCH,
  1INCHDOWN,
  1INCHUP,
  1MBABYDOGE,
  2Z,
  A,
  A2Z,
  AAVE,
  AAVEDOWN,
  AAVEUP,
  ACA,
  ACE,
  ACH,
  ACM,
  ACT,
  ACX,
  ADA,
  ADADOWN,
  ADAUP,
  ADX,
  AE,
  AERGO,
  AEVO,
  AGI,
  AGIX,
  AGLD,
  AI,
  AION,
  AIXBT,
  AKRO,
  ALCX,
  ALGO,
  ALICE,
  ALLO,
  ALPACA,
  ALPHA,
  ALPINE,
  ALT,
  AMB,
  AMP,
  ANC,
  ANIME,
  ANKR,
  ANT,
  ANY,
  APE,
  API3,
  APPC,
  APT,
  AR,
  ARB,
  ARDR,
  ARK,
  ARKM,
  ARN,
  ARPA,
  ARS,
  ASR,
  AST,
  ASTER,
  ASTR,
  AT,
  ATA,
  ATM,
  ATOM,
  AUCTION,
  AUD,
  AUDIO,
  AUTO,
  AVA,
  AVAX,
  AVNT,
  AWE,
  AXL,
  AXS,
  BABY,
  BADGER,
  BAKE,
  BAL,
  BANANA,
  BANANAS31,
  BAND,
  BANK,
  BAR,
  BARD,
  BAT,
  BB,
  BCC,
  BCD,
  BCH,
  BCHA,
  BCHABC,
  BCHDOWN,
  BCHSV,
  BCHUP,
  BCN,
  BCPT,
  BDOT,
  BEAM,
  BEAMX,
  BEAR,
  BEL,
  BERA,
  BETA,
  BETH,
  BFUSD,
  BGBP,
  BICO,
  BIDR,
  BIFI,
  BIGTIME,
  BIO,
  BKRW,
  BLUR,
  BLZ,
  BMT,
  BNB,
  BNBBEAR,
  BNBBULL,
  BNBDOWN,
  BNBUP,
  BNSOL,
  BNT,
  BNX,
  BOME,
  BOND,
  BONK,
  BOT,
  BQX,
  BRD,
  BREV,
  BRL,
  BROCCOLI714,
  BSW,
  BTC,
  BTCB,
  BTCDOWN,
  BTCST,
  BTCUP,
  BTG,
  BTS,
  BTT,
  BTTC,
  BULL,
  BURGER,
  BUSD,
  BVND,
  BZRX,
  C,
  C98,
  CAKE,
  CATI,
  CDT,
  CELO,
  CELR,
  CETUS,
  CFX,
  CGPT,
  CHAT,
  CHESS,
  CHR,
  CHZ,
  CITY,
  CKB,
  CLOAK,
  CLV,
  CMT,
  CND,
  COCOS,
  COMBO,
  COMP,
  COOKIE,
  COP,
  COS,
  COTI,
  COVER,
  COW,
  CREAM,
  CRV,
  CTK,
  CTSI,
  CTXC,
  CVC,
  CVP,
  CVX,
  CYBER,
  CZK,
  D,
  DAR,
  DASH,
  DATA,
  DCR,
  DEGO,
  DENT,
  DEXE,
  DF,
  DGB,
  DGD,
  DIA,
  DLT,
  DNT,
  DOCK,
  DODO,
  DOGE,
  DOGS,
  DOLO,
  DOT,
  DOTDOWN,
  DOTUP,
  DREP,
  DUSK,
  DYDX,
  DYM,
  EASY,
  EDEN,
  EDO,
  EDU,
  EGLD,
  EIGEN,
  ELF,
  ENA,
  ENG,
  ENJ,
  ENS,
  ENSO,
  EOS,
  EOSBEAR,
  EOSBULL,
  EOSDOWN,
  EOSUP,
  EPIC,
  EPS,
  EPX,
  ERA,
  ERD,
  ERN,
  ETC,
  ETH,
  ETHBEAR,
  ETHBULL,
  ETHDOWN,
  ETHFI,
  ETHUP,
  EUL,
  EUR,
  EURI,
  EVX,
  EZ,
  F,
  FARM,
  FET,
  FF,
  FIDA,
  FIL,
  FILDOWN,
  FILUP,
  FIO,
  FIRO,
  FIS,
  FLM,
  FLOKI,
  FLOW,
  FLUX,
  FOGO,
  FOR,
  FORM,
  FORTH,
  FRAX,
  FRONT,
  FTM,
  FTT,
  FUEL,
  FUN,
  FXS,
  G,
  GAL,
  GALA,
  GAS,
  GBP,
  GFT,
  GHST,
  GIGGLE,
  GLM,
  GLMR,
  GMT,
  GMX,
  GNO,
  GNS,
  GNT,
  GO,
  GPS,
  GRS,
  GRT,
  GTC,
  GTO,
  GUN,
  GVT,
  GXS,
  HAEDAL,
  HARD,
  HBAR,
  HC,
  HEGIC,
  HEI,
  HEMI,
  HFT,
  HIFI,
  HIGH,
  HIVE,
  HMSTR,
  HNT,
  HOLO,
  HOME,
  HOOK,
  HOT,
  HSR,
  HUMA,
  HYPER,
  ICN,
  ICP,
  ICX,
  ID,
  IDEX,
  IDR,
  IDRT,
  ILV,
  IMX,
  INIT,
  INJ,
  INS,
  IO,
  IOST,
  IOTA,
  IOTX,
  IQ,
  IRIS,
  JASMY,
  JOE,
  JPY,
  JST,
  JTO,
  JUP,
  JUV,
  KAIA,
  KAITO,
  KAVA,
  KDA,
  KEEP,
  KERNEL,
  KEY,
  KGST,
  KITE,
  KLAY,
  KMD,
  KMNO,
  KNC,
  KP3R,
  KSM,
  LA,
  LAYER,
  LAZIO,
  LDO,
  LEND,
  LEVER,
  LINA,
  LINEA,
  LINK,
  LINKDOWN,
  LINKUP,
  LISTA,
  LIT,
  LOKA,
  LOOM,
  LPT,
  LQTY,
  LRC,
  LSK,
  LTC,
  LTCDOWN,
  LTCUP,
  LTO,
  LUMIA,
  LUN,
  LUNA,
  LUNC,
  MAGIC,
  MANA,
  MANTA,
  MASK,
  MATIC,
  MAV,
  MBL,
  MBOX,
  MC,
  MCO,
  MDA,
  MDT,
  MDX,
  ME,
  MEME,
  MET,
  METIS,
  MFT,
  MINA,
  MIR,
  MIRA,
  MITH,
  MITO,
  MKR,
  MLN,
  MMT,
  MOB,
  MOD,
  MORPHO,
  MOVE,
  MOVR,
  MTH,
  MTL,
  MUBARAK,
  MULTI,
  MXN,
  NANO,
  NAS,
  NAV,
  NBS,
  NCASH,
  NEAR,
  NEBL,
  NEIRO,
  NEO,
  NEWT,
  NEXO,
  NFP,
  NGN,
  NIL,
  NKN,
  NMR,
  NOM,
  NOT,
  NPXS,
  NTRN,
  NU,
  NULS,
  NXPC,
  NXS,
  OAX,
  OCEAN,
  OG,
  OGN,
  OM,
  OMG,
  OMNI,
  ONDO,
  ONE,
  ONG,
  ONT,
  OOKI,
  OP,
  OPEN,
  ORCA,
  ORDI,
  ORN,
  OSMO,
  OST,
  OXT,
  PARTI,
  PAX,
  PDA,
  PENDLE,
  PENGU,
  PEOPLE,
  PEPE,
  PERL,
  PERP,
  PHA,
  PHB,
  PHX,
  PIVX,
  PIXEL,
  PLA,
  PLN,
  PLUME,
  PNT,
  PNUT,
  POA,
  POE,
  POL,
  POLS,
  POLY,
  POLYX,
  POND,
  PORTAL,
  PORTO,
  POWR,
  PPT,
  PROM,
  PROS,
  PROVE,
  PSG,
  PUMP,
  PUNDIX,
  PYR,
  PYTH,
  QI,
  QKC,
  QLC,
  QNT,
  QSP,
  QTUM,
  QUICK,
  RAD,
  RAMP,
  RARE,
  RAY,
  RCN,
  RDN,
  RDNT,
  RED,
  REEF,
  REI,
  REN,
  RENBTC,
  RENDER,
  REP,
  REQ,
  RESOLV,
  REZ,
  RGT,
  RIF,
  RLC,
  RNDR,
  RON,
  RONIN,
  ROSE,
  RPL,
  RPX,
  RSR,
  RUB,
  RUNE,
  RVN,
  S,
  SAGA,
  SAHARA,
  SALT,
  SAND,
  SANTOS,
  SAPIEN,
  SC,
  SCR,
  SCRT,
  SEI,
  SFP,
  SHELL,
  SHIB,
  SIGN,
  SKL,
  SKY,
  SKYCOIN,
  SLF,
  SLP,
  SNGLS,
  SNM,
  SNT,
  SNX,
  SOL,
  SOLV,
  SOMI,
  SOPH,
  SPARTA,
  SPELL,
  SPK,
  SRM,
  SSV,
  STEEM,
  STG,
  STMX,
  STO,
  STORJ,
  STORM,
  STPT,
  STRAT,
  STRAX,
  STRK,
  STX,
  SUB,
  SUI,
  SUN,
  SUPER,
  SUSD,
  SUSHI,
  SUSHIDOWN,
  SUSHIUP,
  SWRV,
  SXP,
  SXPDOWN,
  SXPUP,
  SXT,
  SYN,
  SYRUP,
  SYS,
  T,
  TAO,
  TCT,
  TFUEL,
  THE,
  THETA,
  TIA,
  TKO,
  TLM,
  TNB,
  TNSR,
  TNT,
  TOMO,
  TON,
  TORN,
  TOWNS,
  TRB,
  TREE,
  TRIBE,
  TRIG,
  TROY,
  TRU,
  TRUMP,
  TRX,
  TRXDOWN,
  TRXUP,
  TRY,
  TST,
  TURBO,
  TURTLE,
  TUSDB,
  TUT,
  TVK,
  TWT,
  U,
  UAH,
  UFT,
  UMA,
  UNFI,
  UNI,
  UNIDOWN,
  UNIUP,
  USD,
  USD1,
  USDC,
  USDE,
  USDS,
  USDSB,
  USUAL,
  UTK,
  VAI,
  VANA,
  VANRY,
  VELODROME,
  VEN,
  VET,
  VGX,
  VIA,
  VIB,
  VIBE,
  VIC,
  VIDT,
  VIRTUAL,
  VITE,
  VOXEL,
  VTHO,
  W,
  WABI,
  WAL,
  WAN,
  WAVES,
  WAXP,
  WBETH,
  WBTC,
  WCT,
  WIF,
  WIN,
  WING,
  WINGS,
  WLD,
  WLFI,
  WNXM,
  WOO,
  WPR,
  WRX,
  WTC,
  XAI,
  XEC,
  XEM,
  XLM,
  XLMDOWN,
  XLMUP,
  XMR,
  XNO,
  XPL,
  XRP,
  XRPBEAR,
  XRPBULL,
  XRPDOWN,
  XRPUP,
  XTZ,
  XTZDOWN,
  XTZUP,
  XUSD,
  XVG,
  XVS,
  XZC,
  YB,
  YFI,
  YFIDOWN,
  YFII,
  YFIUP,
  YGG,
  YOYO,
  ZAR,
  ZBT,
  ZEC,
  ZEN,
  ZIL,
  ZK,
  ZKC,
  ZKP,
  ZRO,
  ZRX"
commission: 0.00075
log_level: 1
