---
- name: Providion Harjus instance
  hosts: harjus_instance
  gather_facts: no
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{ playbook_dir }}/../harjus-ec2-key.pem"
    ansible_user: ec2-user
  tasks:
  
    - name: Install packages
      ansible.builtin.package:
        name:
          - tmux
          - htop
          - vim
        state: present
        update_cache: yes

    - name: Install Nix package manager
      ansible.builtin.shell:
        cmd: curl -L https://nixos.org/nix/install | sh -s -- --daemon
        creates: /etc/nix/nix.conf

    - name: Set default nix channels
      ansible.builtin.shell:
        cmd: nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs && nix-channel --update
        creates: /home/{{ ansible_user }}/.nix-defexpr/channels/nixpkgs

    - name: allow unsigned nix packages
      ansible.builtin.lineinfile:
        path: /etc/nix/nix.conf
        line: require-sigs = false
        state: present
      notify: Restart nix-daemon

  handlers:
    - name: Restart nix-daemon
      ansible.builtin.systemd_service:
        name: nix-daemon
        state: restarted
        daemon_reload: yes
