---
- name: Provision Harjus instance
  hosts: harjus_instance
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{ playbook_dir }}/../harjus-ec2-key.pem"
    ansible_user: admin
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - tmux
          - htop
          - vim
          - python3
          - python3-pip
          - python3-boto3
          - python3-botocore
          - python3-packaging
          - tuned
          - sysstat
          - linux-headers-{{ ansible_kernel }}
          - dpdk
          - dpdk-kmods-dkms
          - libdpdk-dev
          - net-tools
          - bc
        state: present
        update_cache: yes

    - name: Enable & start tuned service
      ansible.builtin.systemd:
        name: tuned
        enabled: yes
        state: started

    - name: Create tuned profile directory
      ansible.builtin.file:
        path: /etc/tuned/profiles/harjus
        state: directory
        mode: "0755"

    - name: Create tuned profile
      ansible.builtin.copy:
        src: tuned.conf
        dest: /etc/tuned/profiles/harjus/tuned.conf

    - name: Set tuned profile
      ansible.builtin.command: tuned-adm profile harjus

    - name: Verify tuned profile
      ansible.builtin.command: tuned-adm verify
      register: tuned_verify
      ignore_errors: yes
      changed_when: "tuned_verify.rc != 0"
      failed_when: false
      notify: Reboot

    - name: Blacklist iptables kernel module
      ansible.builtin.copy:
        dest: /etc/modprobe.d/blacklist-iptables.conf
        content: |
          blacklist ip_tables
        owner: root
        group: root
        mode: "0644"
      notify: Reboot

  handlers:
    - name: Reboot
      ansible.builtin.reboot:
