name: Build and Release

# build if push to main
# if tagged with releases/X.Y.Z, deploy additionally to QA

on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+
    branches: main

jobs:
  quality:
    uses: ./.github/workflows/quality.yml

  build:
    runs-on: ubuntu-latest
    needs: [quality]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v14

      - name: Activate nix-shell and build project
        run: |
          nix-shell -A devEnv --run "mix local.hex --force && mix deps.get"
          nix-build

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 137068223640.dkr.ecr.eu-north-1.amazonaws.com
          ECR_REPOSITORY: harjus-ecr-repository
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # - name: Deploy to ECS
      #   if: startsWith(github.ref, 'refs/tags/releases/')
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     TF_VAR_image_tag: ${{ github.sha }}
      #   run: |
      #     cd deploy
      #     terraform -chdir=deploy init
      #     terraform -chdir=deploy apply -auto-approve
