name: Build and Release

# build if push to main
# if tagged with releases/X.Y.Z, deploy additionally to QA

on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+
    branches: main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  quality:
    uses: ./.github/workflows/quality.yml

  build:
    runs-on: ubuntu-latest
    needs: [quality]

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::137068223640:role/GithubAction

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v14

      - name: Activate nix-shell, build, push image to ECR
        env:
          ECR_REGISTRY: 137068223640.dkr.ecr.ap-northeast-1.amazonaws.com
          ECR_REPOSITORY: harjus
          IMAGE_TAG: ${{ github.sha }}
          RELEASE_VERSION: ${{ github.ref_name }}
        run: |
          nix-shell -A devEnv --run "mix local.hex --force && mix deps.get"

          nix-build
          IMAGE=`docker image load -q < result-2|awk '{print $3}'`
          
          docker tag $IMAGE $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

      - name: Tag and Push Release Version
        if: startsWith(github.ref, 'refs/tags/releases/')
        env:
          ECR_REGISTRY: 137068223640.dkr.ecr.ap-northeast-1.amazonaws.com
          ECR_REPOSITORY: harjus
          IMAGE_TAG: ${{ github.sha }}
          RELEASE_VERSION: ${{ github.ref_name }}
        run: |
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.ref_name }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.ref_name }}

      - name: Deploy to ECS
        if: startsWith(github.ref, 'refs/tags/releases/')
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          terraform -chdir=deploy init
          terraform -chdir=deploy apply -var-file="qa.tfvars" -var "image_tag=$IMAGE_TAG" -auto-approve
