name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v14

      - name: Activate nix-shell and run mix quality.ci
        run: |
          nix-shell -p devEnv --run "mix quality.ci"

      - name: Run nix-build
        run: nix-build

      - name: Upload container image
        uses: actions/upload-artifact@v2
        with:
          name: container-image
          path: result-2
