name: Quality check

# This is reusable by other workflows
on:
  workflow_call:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build
        run: |
          nix-shell -A devEnv --run "cmake -S harjus-port -B build"
          nix-shell -A devEnv --run "cmake --build build --config Debug --target all --"

      - name: Test
        run: |
          nix-shell -A devEnv --run "ctest -j10 -C Debug -T test --output-on-failure --test-dir build/"